name: SecurityPipeline

on: [push]

jobs:
  horusec-scan:
    name: Horusec SAST Scan
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: 1. Check out code (Completo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Instalar Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s /usr/local/bin
          echo "Horusec instalado com sucesso!"

      - name: 3. Rodar Scan (Gerando SARIF)
        run: |
          echo "Rodando scan..."
          horusec start -p . \
            -e="true" \
            --disable-docker="true" \
            --ignore="**/node_modules/**" \
            -o="sarif" \
            -O="./horusec-results.sarif" || true

          if [ ! -f "./horusec-results.sarif" ]; then
            echo "Nenhum resultado SARIF gerado. Criando arquivo vazio..."
            echo '{"version":"2.1.0","runs":[]}' > horusec-results.sarif
          fi

          echo "Conteúdo do diretório atual:"
          ls -lah

      - name: 4. Upload do Relatório SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: horusec-results.sarif
          category: gerProjetos-sast
