name: SecurityPipeline (Versão Final)

on: [push]

jobs:
  horusec-scan:
    name: Horusec SAST Scan
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      contents: read

    steps:
      - name: 1. Check out code (Completo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Instalar Horusec
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest /usr/local/bin
          horusec version

      - name: 3. Rodar Scan (Gerando SARIF)
        run: |
          horusec start -p . \
            -e="true" \
            --disable-docker="true" \
            --ignore="**/node_modules/**" \
            -o="sarif" \
            -O="./horusec-results.sarif" || true

          if [ ! -s "./horusec-results.sarif" ]; then
            echo '{"version":"2.1.0","runs":[{"tool":{"driver":{"name":"Horusec","informationUri":"https://github.com/ZupIT/horusec"}},"results":[]}]}'
            > horusec-results.sarif
          fi

          ls -lah

      - name: 4. Upload do Relatório SARIF
        if: always() && hashFiles('horusec-results.sarif') != ''
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: horusec-results.sarif
          category: gerProjetos-sast
